name: Scripts Test

on:
  pull_request:
    paths:
      - .github/scripts/**
      - .github/workflows/scripts-test.yaml

permissions:
  contents: read

jobs:
  test:
    name: Test .github/scripts
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        working-directory: .github/scripts
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: .github/scripts/package-lock.json

      - run: npm ci
      - run: npm test
